### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by Bermudagirl52** [EmilioPelaez/iClassic#1]
I love iClassic but now that I have upgraded to iOS 14 I have found it doesn't support widgets. Is there a possibility you could do something about this?

**Comment by EmilioPelaez** [comment]
iClassic is no longer in development, and given the static nature of the widgets it wouldn't make sense to add an iClassic widget.

**Comment by Bermudagirl52** [comment]
It would or would not make sense?

**Comment by EmilioPelaez** [comment]
Sorry, it wouldn't. I edited my comment.

Thank you for your feedback though.
